# Generated by Django 4.2.11 on 2024-05-08 04:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'estate',
            },
        ),
        migrations.CreateModel(
            name='ServiceContractingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_api_id', models.CharField(max_length=15)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.estate')),
            ],
        ),
        migrations.AddField(
            model_name='estate',
            name='servic_contracting_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estate.servicecontractingplan'),
        ),
    ]
